baseURL = 'https://mybabyiscue.github.io/xiejunlibrary'
languageCode = 'en-us'
timeZone = "Asia/Shanghai"
title = "阿谢"
copyright = "© 阿谢"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  mode="toggle"
  useCDN=false
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/mybabyiscue/xiejunlibrary"

[outputs]
  home = ["HTML", "JSON"]

[menus]
  [[menu.main]]
    name = "Archive"
    url = "/tags"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
  [markup.highlight]
    noClasses = false
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[pagination]
  disablePagination = true