name = 'article'
license = 'MIT'
licenselink = 'https://github.com/henglgh/hugo-theme-article/LICENSE'
description = 'A Hugo theme for articles'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/henglgh/hugo-theme-article'

# If you have a running demo of the theme
demosite = 'https://henglgh.github.io/hugo-theme-article'

# Taxonomy terms
tags = ['blog', 'article']
features = ['global search', 'white/dark theme', 'mobile adaptation']

# If the theme has a single author
[author]
  name = '阿根'
  homepage = 'https://github.com/henglgh'
